[workspace]
members = ["tree-sitter-solar", "solar-system", "solar-shared", "test-utils"]

[workspace.dependencies]
solar-shared = { path = "solar-shared" }
tree-sitter-solar = { path = "tree-sitter-solar" }

[package]
name = "solar"
version = "0.1.0"
edition = "2024"
default-run = "solar"

[dependencies]
annotate-snippets = "0.12.12"
clap = { version = "4.6.6", features = ["derive"] }
rand = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
solar-shared = { workspace = true }
tempdir = "0.3.7"
tree-sitter = "0.25"
tree-sitter-solar = { workspace = true }

[dev-dependencies]
test-utils = { path = "test-utils" }

[profile.release]
lto = false
opt-level = 3
debug = true
