organization:
    id: 1997598a-af9d-45c8-8ab1-72f8a19a2f05
    name: solar-labs
project:
    id: 505d8a13-4114-4f67-af0c-3398ea3671a6
    slug: circleci/4AHcicjVW6jJ3YDoW1hwsz/AvasKNLq8WWQVdZijzhDfB
    name: solar
